apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: service-alerts
spec:
  groups:
  - name: service.rules
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        description: "Error rate is above 10% for 5 minutes"
    - alert: SlowResponses
      expr: http_request_duration_seconds{quantile="0.9"} > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        description: "90th percentile of response times is above 2 seconds" 