apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'transport-service'
        static_configs:
          - targets: ['transport-service:8080']
      - job_name: 'translation-service'
        static_configs:
          - targets: ['translation-service:8000'] 