apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-service
  labels:
    app: translation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translation-service
  template:
    metadata:
      labels:
        app: translation-service
    spec:
      containers:
      - name: translation-service
        image: europe-west12-docker.pkg.dev/${PROJECT_ID}/translation-service/translation-service:${GITHUB_SHA}
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secrets
              key: api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"