apiVersion: apps/v1
kind: Deployment
metadata:
  name: transport-service
  labels:
    app: transport-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transport-service
  template:
    metadata:
      labels:
        app: transport-service
    spec:
      containers:
      - name: transport-service
        image: europe-west12-docker.pkg.dev/${PROJECT_ID}/transport-service/transport-service:${GITHUB_SHA}
        ports:
        - containerPort: 8080  # Добавил порт
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"