apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  DB_HOST: "your-gcp-postgres-host"
  DB_PORT: "5432"
  DB_NAME: "smarttranslate"
---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  DB_USER: c21hcnR0cmFuc2xhdGUtc3Fs
  DB_PASSWORD: U1RzUTEtVXNlcg==